# Generated by Django 4.2.5 on 2023-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='gallery_cart',
        ),
    ]
