# Generated by Django 4.2.6 on 2023-11-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_record_cartrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='shop.cart'),
        ),
    ]
