# Generated by Django 4.2.7 on 2023-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('collecting', 'Collecting'), ('pending', 'Pending Payment'), ('payed', 'Payed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='collecting', max_length=255),
        ),
    ]
