# Generated by Django 4.2.7 on 2023-12-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cart_order_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='cost',
            new_name='price',
        ),
    ]
