# Generated by Django 4.2.6 on 2023-10-29 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('name', models.SlugField(unique=True)),
            ],
        ),
    ]
