# Generated by Django 4.2.6 on 2023-11-03 14:28

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_textblockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='prefs/')),
            ],
            options={
                'verbose_name': 'Изоражение Сайта',
                'verbose_name_plural': 'Изоражения Сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='textblockmodel',
            options={'verbose_name': 'Блок текста', 'verbose_name_plural': 'Блоки текста'},
        ),
    ]
