# Generated by Django 4.2.6 on 2023-11-08 14:49

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_textblockmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='main/')),
                ('index', models.PositiveIntegerField()),
            ],
        ),
    ]
