# Generated by Django 4.2.5 on 2023-09-10 14:12

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=40, verbose_name='Название статьи')),
                ('article_text', models.TextField(max_length=2000, verbose_name='Текст статьи')),
                ('article_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='media/')),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
