# Generated by Django 4.2.5 on 2023-09-14 12:34

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
