# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_articlemodel_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.articlemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('gallery', models.ManyToManyField(through='Blog.GalleryImage', to='Blog.articlemodel')),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.image'),
        ),
    ]
