# Generated by Django 4.2.5 on 2023-09-20 14:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_galleryimage_image_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='article_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
