# Generated by Django 4.2.5 on 2023-09-21 11:59

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_articlemodel_article_image_remove_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article_image',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
